;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env2,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c2,$c3,$c6,$c8,$cc,$ce,$00,$05
@env2:
	.byte $bb,$bc,$bd,$c0,$00,$03


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$38,$38,$38,$38,$38,$38,$38,$38,$3e,$3e,$3e,$3e,$3e,$3e,$3e
	.byte $38,$38,$38,$38,$38,$38,$38,$38,$38,$3e,$3e,$3e,$3e,$3e,$3e,$3e
	.byte $3e,$3e,$38,$38,$38,$38,$38,$38,$38,$38,$38,$3e,$3e,$3e,$3e,$3e
	.byte $3e,$3e,$3e,$3e,$38,$38,$38,$38,$38,$38,$38,$38,$38,$3e,$3e,$3e
	.byte $3e
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref1:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref3:
	.byte $80,$18,$18,$18,$18,$87,$18,$18,$18,$87,$18,$18,$18,$89,$18,$18
	.byte $18,$91,$18,$18,$18,$8f,$18,$18,$18,$8f,$18,$18,$18,$87
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
